# Generated by Django 2.0.6 on 2020-05-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.TextField()),
                ('days', models.TextField()),
                ('water', models.TextField()),
                ('infoDaylight', models.TextField()),
                ('warnings', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
