# Generated by Django 2.0.6 on 2020-05-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('link_text', models.CharField(max_length=12)),
                ('link_href', models.URLField()),
            ],
        ),
    ]
